// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAK1oql7EeQFHbQ9PDVVVIp6LLCTWPzUQ',
    appId: '1:88411633570:web:dccdb67128ce2ad37ca4fb',
    messagingSenderId: '88411633570',
    projectId: 'instagram-34487',
    authDomain: 'instagram-34487.firebaseapp.com',
    storageBucket: 'instagram-34487.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHk_uwzAfqKLjktpiVXf21W9FVSdXm6nE',
    appId: '1:88411633570:android:399293573356f4747ca4fb',
    messagingSenderId: '88411633570',
    projectId: 'instagram-34487',
    storageBucket: 'instagram-34487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtOagf0Nr_XXC8b4fITs3kMYtw_MJTr4',
    appId: '1:88411633570:ios:c24c868494a887f97ca4fb',
    messagingSenderId: '88411633570',
    projectId: 'instagram-34487',
    storageBucket: 'instagram-34487.appspot.com',
    iosBundleId: 'com.example.instagramClone1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtOagf0Nr_XXC8b4fITs3kMYtw_MJTr4',
    appId: '1:88411633570:ios:c24c868494a887f97ca4fb',
    messagingSenderId: '88411633570',
    projectId: 'instagram-34487',
    storageBucket: 'instagram-34487.appspot.com',
    iosBundleId: 'com.example.instagramClone1',
  );
}
